### ISSUE TITLE
HPCD/LPCD swapping

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/common-issues#2]
### Background
- 2 HPCDs of ITMX did not receive the WD pulse properly.

### Todo
- [ ] detach diode and change the resistance of LPCD (5 of them. originally assigned for Cryo-payload)
- [ ] swap 2 HPCDs to modified LPCDs
- [ ] ask inspection of the WD circuits to AELs
- [ ] re-install the HPCD to ITMX.

**Comment by YoshinoriFujii** [comment]
done.
